homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data
  elevation: !secret home_elev
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # customization
  customize: !include customize.yaml

zone:
  name: school
  latitude: !secret school_lat
  longitude: !secret school_long
  icon: mdi:school
zone 2:
  name: work_d
  latitude: !secret work_d_lat
  longitude: !secret work_d_long
  icon: mdi:worker

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret front_end_pw
  ssl_certificate: ssl/SSLcertificate.crt
  ssl_key: ssl/SSLprivatekey.key

logger:
  default: warn

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_days: 14
  db_url: !secret db_url

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity

sensor 2:
  platform: transmission
  host: !secret transmission_host
  port: 9091
  name: Transmission
  username: !secret transmission_user
  password: !secret transmission_pw
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

media_player:
  platform: pioneer
  host: !secret pioneer_host
  name: A/V Pioneer

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pw

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    username: !secret ddwrt_username
    password: !secret ddwrt_pw
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: yes
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 30
    # Seconds to wait till marking someone as not home after not being seen
    # (default: 180)
    consider_home: 180
  - platform: owntracks
    max_gps_accuracy: 200

switch:
  platform: transmission
  host: !secret transmission_host
  port: 9091
  name: Transmission
  username: !secret transmission_user
  password: !secret transmission_pw

group: !include group.yaml

automation: !include automation.yaml
